"""init

Revision ID: 1e2a4d30fc67
Revises: 53754b2c08a4
Create Date: 2022-12-27 14:38:38.547359

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "1e2a4d30fc67"
down_revision = "53754b2c08a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_song_artist", table_name="song")
    op.drop_index("ix_song_id", table_name="song")
    op.drop_index("ix_song_name", table_name="song")
    op.drop_index("ix_song_year", table_name="song")
    op.drop_table("song")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "song",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("artist", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="song_pkey"),
    )
    op.create_index("ix_song_year", "song", ["year"], unique=False)
    op.create_index("ix_song_name", "song", ["name"], unique=False)
    op.create_index("ix_song_id", "song", ["id"], unique=False)
    op.create_index("ix_song_artist", "song", ["artist"], unique=False)
    # ### end Alembic commands ###
