"""add year

Revision ID: 53754b2c08a4
Revises: f9c634db477d
Create Date: 2021-09-10 00:52:38.668620

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "53754b2c08a4"
down_revision = "f9c634db477d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("song", sa.Column("year", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_song_year"), "song", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_song_year"), table_name="song")
    op.drop_column("song", "year")
    # ### end Alembic commands ###
