"""add_year

Revision ID: 94598cb1fa7b
Revises: bf9bd33c0c06
Create Date: 2021-09-08 23:27:31.948299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '94598cb1fa7b'
down_revision = 'bf9bd33c0c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_song_year'), 'song', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_year'), table_name='song')
    op.drop_column('song', 'year')
    # ### end Alembic commands ###
